### ISSUE TITLE
0で割れてしまう

### ISSUE THREAD

**Issue by horiyu** [taichiaaa/git-boot-camp-20181130-work1#4]
## 操作手順
* 割り算で，a÷0を計算したら
* 0になった

## 本来の想定
* 割り算で，a÷0を計算したら
* エラーを出してほしい

## 操作環境
* OS: macOS
* OSバージョン: Sequoia
* ブラウザ: Arc
* ブラウザバージョン

**Comment by moridora** [comment]
#7 で解決済み
